// Citizen Interface JavaScript
// Search, platform catalogue, process detail pages, contribution lists and
// type-aware resource inspection (DelibAI / CrowdLaw integration).
const API_BASE = '/api';
const DKG_BASE = 'https://dkg.svagnoni.linkeddata.es';

// State
let currentResults = [];
let currentProcess = null;          // summary object of the process being viewed
let currentParticipants = [];
let currentParticipantsPage = 1;
let contribState = { uri: null, offset: 0, limit: 10, total: 0, kind: '', condition: '', topic: '', order: 'asc' };
let lastFocusedElement = null;
let searchFacets = {};

const TYPE_LABELS = {
    contribution: 'Contribution',
    seed_contribution: 'Seed comment (process design)',
    legal_provision: 'Legal provision',
    topic: 'Topic',
    process: 'Process',
    ai_feedback: 'AI feedback (advice)',
    ai_rewrite: 'AI rewrite suggestion'
};
const KIND_LABELS = { main: 'First-level comment', reply_agree: 'Reply (agrees)', reply_disagree: 'Reply (disagrees)', seed: 'Seed comment', comment: 'Comment' };
const CONDITION_LABELS = { delibai_on: 'AI feedback active', delibai_off: 'AI feedback inactive' };
const STATUS_LABELS = {
    'pilot-historical': 'Historical pilot data',
    'synthetic-evaluation': 'Synthetic evaluation data',
    'derived-annotation': 'Derived annotation',
    'demo': 'Demonstration data'
};
const STATUS_NOTES = {
    'pilot-historical': 'Data collected during a real pilot. Participants are pseudonymised; questionnaires, behavioural logs and credentials are not published.',
    'synthetic-evaluation': 'Comments were generated by the research team to evaluate a prototype. They are not opinions of real citizens and this is not a real public consultation.'
};
const ACTION_LABELS = {
    accepted: 'Feedback seen, text submitted',
    ignored: 'Feedback ignored',
    rejected: 'Label rejected',
    confirmed: 'Label confirmed',
    corrected: 'Label corrected',
    cleared: 'Evaluation withdrawn',
    problem_flagged: 'Problem flagged',
    no_problem: 'No problem found'
};
const STANCE_LABELS = { pro: 'in favour', contro: 'against', neutro: 'neutral', altro: 'other / unclear' };

// ---------------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------------
document.addEventListener('DOMContentLoaded', () => {
    loadStats();
    loadPlatforms();
    setupEventListeners();
    handleDeepLinks();
});

function setupEventListeners() {
    const searchBtn = document.getElementById('searchBtn');
    const searchInput = document.getElementById('searchInput');
    searchBtn.addEventListener('click', performSearch);
    searchInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') performSearch(); });
    searchInput.addEventListener('input', handleAutocomplete);

    const toggle = document.getElementById('filtersToggle');
    if (toggle) {
        toggle.addEventListener('click', () => {
            const panel = document.getElementById('advancedFilters');
            const open = panel.classList.toggle('open');
            toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
        });
    }
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Escape') {
            const modal = document.getElementById('resourceModal');
            if (modal && modal.style.display !== 'none') closeResourceModal();
        }
    });
    window.addEventListener('popstate', () => handleDeepLinks(true));
}

function handleDeepLinks(fromHistory) {
    const params = new URLSearchParams(window.location.search);
    const processUri = params.get('process');
    const resourceUri = params.get('show_resource');
    const q = params.get('q');
    if (q && !fromHistory) {
        document.getElementById('searchInput').value = q;
        if (params.get('platform')) setSelectValue('platformFilter', params.get('platform'));
        if (params.get('mode')) setSelectValue('searchMode', params.get('mode'));
        performSearch(true);
    }
    if (processUri) viewProcess(processUri, true);
    if (resourceUri) showResourceDetails(resourceUri, true);
}

function setSelectValue(id, value) {
    const el = document.getElementById(id);
    if (!el) return;
    let found = false;
    for (const o of el.options) { if (o.value === value) { found = true; break; } }
    if (!found) { const o = document.createElement('option'); o.value = value; o.textContent = value; el.appendChild(o); }
    el.value = value;
}

function pushUrl(params) {
    const url = new URL(window.location.href);
    url.search = '';
    Object.entries(params).forEach(([k, v]) => { if (v) url.searchParams.set(k, v); });
    window.history.pushState({}, document.title, url.toString());
}

// ---------------------------------------------------------------------------
// Stats + platform catalogue
// ---------------------------------------------------------------------------
async function loadStats() {
    try {
        const response = await fetch(`${API_BASE}/stats`);
        const data = await response.json();
        document.getElementById('stats').innerHTML = `
            <div class="stat-card"><div class="stat-number">${fmtNum(data.total_processes)}</div><div class="stat-label">Deliberation Processes</div></div>
            <div class="stat-card"><div class="stat-number">${fmtNum(data.total_contributions)}</div><div class="stat-label">Contributions</div></div>
            <div class="stat-card"><div class="stat-number">${fmtNum(data.total_fallacies)}</div><div class="stat-label">Detected Fallacies</div></div>
            <div class="stat-card"><div class="stat-number">${data.platforms ? data.platforms.length : 0}</div><div class="stat-label">Platforms</div></div>`;

        if (data.platforms && Array.isArray(data.platforms)) {
            const platformFilter = document.getElementById('platformFilter');
            platformFilter.innerHTML = '<option value="">All Platforms</option>';
            data.platforms.filter(p => p && typeof p === 'string' && p.trim().length > 0).sort().forEach(platform => {
                const option = document.createElement('option');
                option.value = platform; option.textContent = platform;
                platformFilter.appendChild(option);
            });
        }
        searchFacets = data.search_facets || {};
        populateFacetSelect('languageFilter', searchFacets.languages, { en: 'English', it: 'Italian', es: 'Spanish', ca: 'Catalan', de: 'German', fr: 'French' });
        populateFacetSelect('documentFilter', searchFacets.documents);
    } catch (error) {
        console.error('Error loading stats:', error);
        document.getElementById('stats').innerHTML = `
            <div class="stat-card" style="grid-column: 1 / -1;"><div class="stat-label" style="color: var(--error-color);">
                <i class="fas fa-exclamation-triangle"></i> Unable to load statistics. Please refresh the page.</div></div>`;
    }
}

function populateFacetSelect(id, facet, labels) {
    const el = document.getElementById(id);
    if (!el || !facet) return;
    const current = el.value;
    el.innerHTML = '<option value="">Any</option>';
    Object.entries(facet).sort((a, b) => b[1] - a[1]).forEach(([value, count]) => {
        const o = document.createElement('option');
        o.value = value;
        o.textContent = `${(labels && labels[value]) || truncate(value, 60)} (${fmtNum(count)})`;
        el.appendChild(o);
    });
    if (current) el.value = current;
}

async function loadPlatforms() {
    const grid = document.getElementById('platformGrid');
    if (!grid) return;
    try {
        const response = await fetch(`${API_BASE}/platforms`);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        const platforms = data.platforms || [];
        if (!platforms.length) { grid.innerHTML = '<p class="empty-state">No platforms found in the graph.</p>'; return; }
        grid.innerHTML = platforms.map(p => `
            <button type="button" class="platform-card" data-platform="${escapeAttr(p.name)}" data-uri="${escapeAttr(p.uri)}" aria-label="${escapeAttr(p.name)}: ${p.processes_count} processes, ${p.contributions_count} contributions">
                <div class="platform-logo-box">${p.logo ? `<img src="${escapeAttr(p.logo)}" alt="${escapeAttr(p.logo_alt || p.name + ' logo')}" loading="lazy">` : `<span class="logo-fallback">${escapeHtml(p.name)}</span>`}</div>
                <h3>${escapeHtml(p.name)}</h3>
                <p>${escapeHtml(truncate(p.description || '', 160))}</p>
                <div class="platform-meta">
                    <span><i class="fas fa-folder-open" aria-hidden="true"></i> ${fmtNum(p.processes_count)} process${p.processes_count === 1 ? '' : 'es'}</span>
                    <span><i class="fas fa-comments" aria-hidden="true"></i> ${fmtNum(p.contributions_count)} contributions</span>
                    ${p.date_from ? `<span><i class="fas fa-calendar" aria-hidden="true"></i> ${escapeHtml(p.date_from)}${p.date_to && p.date_to !== p.date_from ? ' – ' + escapeHtml(p.date_to) : ''}</span>` : ''}
                    ${(p.languages || []).length ? `<span><i class="fas fa-language" aria-hidden="true"></i> ${escapeHtml(p.languages.join(', '))}</span>` : ''}
                </div>
                ${(p.dataset_status || []).map(s => `<span class="badge badge-status">${escapeHtml(STATUS_LABELS[s] || s)}</span>`).join(' ')}
                ${p.logo && p.logo_official === false ? '<p style="font-size:0.72rem;color:var(--text-light);margin:0;">Fallback brand mark – no official logo available</p>' : ''}
            </button>`).join('');
        grid.querySelectorAll('.platform-card').forEach(card => {
            card.addEventListener('click', () => openPlatform(platforms.find(p => p.uri === card.dataset.uri)));
        });
    } catch (error) {
        console.error('Error loading platforms:', error);
        grid.innerHTML = '<p class="error-state"><i class="fas fa-exclamation-circle"></i> Unable to load the platform catalogue.</p>';
    }
}

function openPlatform(p) {
    if (!p) return;
    setSelectValue('platformFilter', p.name);
    if (p.processes && p.processes.length === 1) { viewProcess(p.processes[0].uri); return; }
    if (p.processes && p.processes.length > 1) {
        backToResults();
        const resultsContainer = document.getElementById('searchResults');
        resultsContainer.innerHTML = `
            <div class="notice notice-muted"><strong>${escapeHtml(p.name)}</strong> – ${escapeHtml(p.description || '')}
            ${p.url ? ` <a href="${escapeAttr(p.url)}" target="_blank" rel="noopener">Platform website <i class="fas fa-external-link-alt" aria-hidden="true"></i></a>` : ''}</div>
            ${p.processes.map(pr => `
                <div class="result-card" role="button" tabindex="0" data-uri="${escapeAttr(pr.uri)}">
                    <div class="result-header"><h3>${escapeHtml(pr.title)}</h3></div>
                    <div class="result-meta"><span><i class="fas fa-globe"></i> ${escapeHtml(p.name)}</span></div>
                </div>`).join('')}`;
        bindResultCards(resultsContainer);
        resultsContainer.scrollIntoView({ behavior: 'smooth', block: 'start' });
        return;
    }
    // many processes: run a search restricted to the platform
    const input = document.getElementById('searchInput');
    if (!input.value.trim()) input.value = p.name;
    performSearch();
}

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------
function collectFilters() {
    const val = id => { const el = document.getElementById(id); return el ? el.value.trim() : ''; };
    const contentType = val('contentTypeFilter');
    const filters = {
        platform: val('platformFilter') || null,
        sort_by: val('sortBy') || 'relevance',
        mode: val('searchMode') || 'process',
        content_types: contentType ? [contentType] : null,
        languages: val('languageFilter') ? [val('languageFilter')] : null,
        document: val('documentFilter') || null,
        topic: val('topicFilter') || null,
        date_from: val('dateFrom') || null,
        date_to: val('dateTo') || null,
        include_ai_feedback: !!(document.getElementById('includeAiFeedback') && document.getElementById('includeAiFeedback').checked)
    };
    const minContributions = val('minContributions');
    if (minContributions) filters.min_contributions = parseInt(minContributions);
    return filters;
}

async function performSearch(skipUrl) {
    const query = document.getElementById('searchInput').value.trim();
    if (!query) return;
    backToResults();
    const topK = parseInt(document.getElementById('topK').value);
    const filters = collectFilters();
    if (!skipUrl) pushUrl({ q: query, platform: filters.platform, mode: filters.mode !== 'process' ? filters.mode : null });
    showLoading();
    try {
        const response = await fetch(`${API_BASE}/semantic-search`, {
            method: 'POST', headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ query, top_k: topK, ...filters })
        });
        const data = await response.json();
        if (!response.ok) { showError(data.error || `Search failed (HTTP ${response.status})`); return; }
        currentResults = data.results || [];
        if (data.mode === 'items') displayItemResults(currentResults, data); else displayResults(currentResults, data);
    } catch (error) {
        console.error('Search error:', error);
        showError('Search error. Please try again.');
    }
}

function filterSummary(metadata) {
    const filters = [];
    const f = (metadata && metadata.filters) || {};
    if (f.platform) filters.push(`Platform: ${f.platform}`);
    if (f.min_contributions) filters.push(`Min. ${f.min_contributions} contributions`);
    if (f.content_types) filters.push(`Type: ${f.content_types.map(t => TYPE_LABELS[t] || t).join(', ')}`);
    if (f.languages) filters.push(`Language: ${f.languages.join(', ')}`);
    if (f.document) filters.push(`Document: ${truncate(f.document, 40)}`);
    if (f.topic) filters.push(`Topic: ${f.topic}`);
    if (f.date_from || f.date_to) filters.push(`Date: ${f.date_from || '…'} – ${f.date_to || '…'}`);
    if (f.include_ai_feedback) filters.push('AI feedback included');
    if (metadata && metadata.sort_by && metadata.sort_by !== 'relevance') filters.push(`Sorted by: ${{ contributions: 'Most Contributions', date: 'Most Recent' }[metadata.sort_by] || metadata.sort_by}`);
    if (!filters.length) return '';
    return `<div class="notice notice-muted" style="margin-top:0;"><i class="fas fa-filter" aria-hidden="true"></i> Active filters: ${escapeHtml(filters.join(' • '))}${metadata && metadata.total_results ? ` • ${metadata.total_results} results` : ''}</div>`;
}

function typeBadge(type, isAi) {
    const label = TYPE_LABELS[type] || type || 'Contribution';
    return `<span class="badge ${isAi ? 'badge-ai' : 'badge-type'}">${isAi ? '<i class="fas fa-robot" aria-hidden="true"></i> ' : ''}${escapeHtml(label)}</span>`;
}

function displayResults(results, metadata) {
    const resultsContainer = document.getElementById('searchResults');
    if (!results || results.length === 0) { resultsContainer.innerHTML = emptyState('No results found', 'Try different keywords or adjust filters'); return; }
    const resultsHTML = results.map(result => {
        const matches = (result.matching_contributions || []).slice(0, 2);
        return `
        <div class="result-card" role="button" tabindex="0" data-uri="${escapeAttr(result.uri)}" aria-label="Open process ${escapeAttr(result.title || 'Untitled Process')}">
            <div class="result-header">
                <h3>${escapeHtml(result.title || 'Untitled Process')}</h3>
                <span class="relevance-score" title="Similarity of the best matching document to your query. Not a measure of agreement or importance.">${(result.relevance_score * 100).toFixed(1)}%</span>
            </div>
            <div class="result-type-row">
                <span class="badge badge-type"><i class="fas fa-globe" aria-hidden="true"></i> ${escapeHtml(result.platform || 'Unknown')}</span>
                ${result.dataset_status ? `<span class="badge badge-status">${escapeHtml(STATUS_LABELS[result.dataset_status] || result.dataset_status)}</span>` : ''}
                ${result.language ? `<span class="badge badge-condition">${escapeHtml(result.language)}</span>` : ''}
            </div>
            <p class="description">${escapeHtml(truncate(result.description || '', 200))}</p>
            ${matches.map(m => `<div class="result-snippet">${typeBadge(m.type, m.is_ai_generated)} ${m.topic ? `<span class="badge badge-condition">${escapeHtml(m.topic)}</span>` : ''}<br>${escapeHtml(m.text)}</div>`).join('')}
            <div class="result-meta">
                <span><i class="fas fa-calendar"></i> ${escapeHtml(result.date || 'N/A')}</span>
                <span><i class="fas fa-comments"></i> ${fmtNum(result.contributions_count || 0)} contributions</span>
                <span><i class="fas fa-exclamation-triangle"></i> ${result.fallacies_count || 0} fallacies</span>
            </div>
        </div>`;
    }).join('');
    resultsContainer.innerHTML = filterSummary(metadata) + resultsHTML;
    bindResultCards(resultsContainer);
}

function displayItemResults(results, metadata) {
    const resultsContainer = document.getElementById('searchResults');
    if (!results || results.length === 0) { resultsContainer.innerHTML = emptyState('No matching documents', 'Try different keywords or adjust filters'); return; }
    const note = `<p class="filters-help" style="margin:0.5rem 0 1rem;"><i class="fas fa-info-circle" aria-hidden="true"></i> Scores rank documents by textual closeness to your query. They are not evidence of agreement, influence or derivation.</p>`;
    const html = results.map(r => `
        <div class="result-card" data-uri="${escapeAttr(r.uri)}" data-item="1">
            <div class="result-header">
                <div class="result-type-row" style="margin:0;">
                    ${typeBadge(r.type, r.is_ai_generated)}
                    <span class="badge badge-type"><i class="fas fa-globe" aria-hidden="true"></i> ${escapeHtml(r.platform || '')}</span>
                    ${r.language ? `<span class="badge badge-condition">${escapeHtml(r.language)}</span>` : ''}
                    ${r.date ? `<span class="badge badge-condition"><i class="fas fa-calendar" aria-hidden="true"></i> ${escapeHtml(r.date)}</span>` : ''}
                    ${r.topic ? `<span class="badge badge-condition">${escapeHtml(r.topic)}</span>` : ''}
                    ${r.stance ? `<span class="badge badge-stance-${escapeAttr(r.stance)}">stance: ${escapeHtml(STANCE_LABELS[r.stance] || r.stance)}</span>` : ''}
                    ${r.condition ? `<span class="badge badge-condition">${escapeHtml(CONDITION_LABELS[r.condition] || r.condition)}</span>` : ''}
                    ${r.model ? `<span class="badge badge-ai">${escapeHtml(r.model)}</span>` : ''}
                </div>
                <span class="relevance-score">${(r.similarity_score * 100).toFixed(1)}%</span>
            </div>
            <div class="result-snippet">${escapeHtml(r.snippet || r.text)}</div>
            ${r.document ? `<p style="font-size:0.85rem;color:var(--text-light);margin:0.5rem 0 0;"><i class="fas fa-gavel" aria-hidden="true"></i> ${escapeHtml(r.document)}${r.provision ? ' – ' + escapeHtml(r.provision) : ''}</p>` : ''}
            ${r.is_ai_generated && r.annotates ? `<p style="font-size:0.85rem;color:var(--text-light);margin:0.5rem 0 0;"><i class="fas fa-robot" aria-hidden="true"></i> AI-generated feedback on a participant's contribution – not a participant's opinion.</p>` : ''}
            <div class="result-links">
                <button type="button" class="link-button" data-inspect="${escapeAttr(r.uri)}"><i class="fas fa-search-plus" aria-hidden="true"></i> Inspect</button>
                ${r.is_ai_generated && r.annotates ? `<button type="button" class="link-button" data-inspect="${escapeAttr(r.annotates)}"><i class="fas fa-comment" aria-hidden="true"></i> Annotated contribution</button>` : ''}
                ${r.process ? `<button type="button" class="link-button" data-process="${escapeAttr(r.process)}"><i class="fas fa-folder-open" aria-hidden="true"></i> ${escapeHtml(truncate(r.process_name || 'Process', 60))}</button>` : ''}
                <a href="${escapeAttr(r.uri)}" target="_blank" rel="noopener" title="Linked-data URI (content negotiation)"><i class="fas fa-link" aria-hidden="true"></i> URI</a>
            </div>
        </div>`).join('');
    resultsContainer.innerHTML = filterSummary(metadata) + note + html;
    bindInspectButtons(resultsContainer);
}

function bindResultCards(container) {
    container.querySelectorAll('.result-card[data-uri]:not([data-item])').forEach(card => {
        card.addEventListener('click', () => viewProcess(card.dataset.uri));
        card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); viewProcess(card.dataset.uri); } });
    });
}

function bindInspectButtons(container) {
    container.querySelectorAll('[data-inspect]').forEach(b => b.addEventListener('click', (e) => { e.stopPropagation(); showResourceDetails(b.dataset.inspect); }));
    container.querySelectorAll('[data-process]').forEach(b => b.addEventListener('click', (e) => { e.stopPropagation(); closeResourceModal(); viewProcess(b.dataset.process); }));
}

// ---------------------------------------------------------------------------
// Process detail page
// ---------------------------------------------------------------------------
async function viewProcess(uri, skipUrl) {
    showLoading();
    if (!skipUrl) pushUrl({ process: uri });
    try {
        const [summaryRes, legacyRes] = await Promise.all([
            fetch(`${API_BASE}/process/summary?uri=${encodeURIComponent(uri)}`),
            fetch(`${API_BASE}/process?uri=${encodeURIComponent(uri)}`)
        ]);
        if (!summaryRes.ok) {
            const err = await summaryRes.json().catch(() => ({}));
            showError(err.error === 'Process not found' ? 'This process does not exist in the knowledge graph.' : 'Error loading process details');
            return;
        }
        const summary = await summaryRes.json();
        const legacy = legacyRes.ok ? await legacyRes.json() : {};
        currentProcess = { ...legacy, ...summary };
        displayProcessDetails(currentProcess);
    } catch (error) {
        console.error('Error loading process:', error);
        showError('Error loading process details');
    }
}

function displayProcessDetails(process) {
    const resultsContainer = document.getElementById('searchResults');
    const detailsContainer = document.getElementById('processDetails');
    resultsContainer.style.display = 'none';
    detailsContainer.style.display = 'block';

    currentParticipants = process.participants || [];
    currentParticipantsPage = 1;
    const s = process.stats || {};
    const totalAll = s.contributions || process.contributions_count || 0;
    contribState = { uri: process.uri, offset: 0, limit: 10, total: totalAll, totalAll, kind: '', condition: '', topic: '', order: 'asc' };

    const statusNote = process.dataset_status && STATUS_NOTES[process.dataset_status]
        ? `<div class="notice ${process.dataset_status === 'synthetic-evaluation' ? 'notice-warn' : 'notice-info'}"><strong>${escapeHtml(STATUS_LABELS[process.dataset_status])}.</strong> ${escapeHtml(STATUS_NOTES[process.dataset_status])}</div>` : '';

    const tiles = [
        ['Contributions', s.contributions ?? process.contributions_count ?? 0],
        s.participants ? ['Contributing participants', s.participants] : null,
        s.by_kind && s.by_kind.main ? ['First-level comments', s.by_kind.main] : null,
        s.by_kind && (s.by_kind.reply_agree || s.by_kind.reply_disagree) ? ['Replies', (s.by_kind.reply_agree || 0) + (s.by_kind.reply_disagree || 0)] : null,
        s.ai_feedback ? ['AI feedback records', s.ai_feedback] : null,
        s.ai_fallacy_flags ? ['AI fallacy flags', s.ai_fallacy_flags] : null,
        s.peer_evaluations ? ['Peer evaluations', s.peer_evaluations] : null,
        s.recorded_responses ? ['Responses to AI labels', s.recorded_responses] : null,
        s.anchors_user ? ['User-chosen anchors', s.anchors_user] : null,
        s.anchors_system ? ['System-resolved anchors', s.anchors_system] : null,
        (process.fallacies || []).length ? ['Detected fallacies', process.fallacies.length] : null
    ].filter(Boolean);

    const stanceHtml = s.stance_labels && Object.keys(s.stance_labels).length
        ? `<p style="font-size:0.9rem;"><strong>Automatic stance labels:</strong> ${Object.entries(s.stance_labels).map(([k, v]) => `<span class="badge badge-stance-${escapeAttr(k)}">${escapeHtml(STANCE_LABELS[k] || k)}: ${v}</span>`).join(' ')} <span style="color:var(--text-light)">(model output, see each contribution for method and confidence)</span></p>` : '';
    const conditionHtml = s.by_condition && Object.keys(s.by_condition).length
        ? `<p style="font-size:0.9rem;"><strong>Experimental conditions:</strong> ${Object.entries(s.by_condition).map(([k, v]) => `<span class="badge badge-condition">${escapeHtml(CONDITION_LABELS[k] || k)}: ${v}</span>`).join(' ')}</p>` : '';

    const topics = process.topics || [];
    const topicsHtml = topics.length ? `
        <div class="section">
            <h3><i class="fas fa-tags"></i> Topics (${topics.length})</h3>
            <div class="topic-chips" role="group" aria-label="Filter contributions by topic">
                <button type="button" class="topic-chip active" data-topic="">All</button>
                ${topics.map(t => `<button type="button" class="topic-chip" data-topic="${escapeAttr(t.uri)}" title="${escapeAttr(t.description || t.top_terms || '')}">${escapeHtml(truncate(t.label, 60))} (${t.contributions_count})</button>`).join('')}
            </div>
            ${topics.filter(t => t.description).map(t => `<p style="font-size:0.9rem;margin:0.6rem 0 0;"><strong>${escapeHtml(t.label)}:</strong> ${escapeHtml(t.description)} <button type="button" class="link-button" data-inspect="${escapeAttr(t.uri)}">details</button></p>`).join('')}
            ${topics.some(t => t.method) ? `<p class="filters-help">These topics are automatic clusters (${escapeHtml(topics.find(t => t.method).method.replace(/_/g, ' '))}); their labels are the top terms of each cluster.</p>` : ''}
        </div>` : '';

    const legalHtml = (process.legal_documents || []).length ? `
        <div class="section">
            <h3><i class="fas fa-gavel"></i> Legislative text under consultation</h3>
            ${process.legal_documents.map(d => `
                <div class="legal-doc-card">
                    <p style="margin:0;"><strong>${escapeHtml(d.label)}</strong> ${d.language ? `<span class="badge badge-condition">${escapeHtml(d.language)}</span>` : ''}</p>
                    <p class="mono" style="margin:0.3rem 0;color:var(--text-light);">expression ${escapeHtml(d.frbr_expression)}${d.filename ? ' • ' + escapeHtml(d.filename) : ''}</p>
                    <p style="font-size:0.85rem;margin:0.3rem 0;">Comments are anchored to this exact version of the text (FRBR expression); correspondences are not transferred to later versions. <button type="button" class="link-button" data-inspect="${escapeAttr(d.uri)}">Inspect document</button></p>
                    <ul class="provision-list">
                        ${d.provisions.map(p => `<li><button type="button" data-inspect="${escapeAttr(p.uri)}">${escapeHtml(truncate(p.label, 70))} <span style="color:var(--text-light)">(${p.anchored_contributions} anchored)</span></button></li>`).join('')}
                    </ul>
                </div>`).join('')}
        </div>` : '';

    const links = process.links || [];
    const linksHtml = links.length ? `
        <div class="section">
            <h3><i class="fas fa-link"></i> Links to other processes and vocabularies (${links.length})</h3>
            <p class="filters-help">Explicit links are documented in the source data. Inferred links are automatic thematic associations with a similarity score; they never assert influence, derivation or agreement.</p>
            <ul class="links-list">${links.map(linkItem).join('')}</ul>
        </div>` : '';

    const metrics = process.evaluation_metrics || [];
    const metricsHtml = metrics.length ? `
        <div class="section">
            <h3><i class="fas fa-chart-bar"></i> Evaluation metrics reported for this corpus</h3>
            <p class="filters-help">Prototype evaluation figures (anchoring and stance accuracy against the seeded ground truth), as recorded in the source repository.</p>
            <dl class="inspect-kv">${metrics.filter(m => /accuracy|macro_f1|total|correct/.test(m.name)).slice(0, 24).map(m => `<dt>${escapeHtml(m.name)}</dt><dd>${escapeHtml(fmtMetric(m.value))}</dd>`).join('')}</dl>
        </div>` : '';

    const ds = process.dataset;
    const provenanceHtml = ds ? `
        <div class="section">
            <h3><i class="fas fa-history"></i> Origin and provenance</h3>
            <dl class="inspect-kv">
                <dt>Dataset</dt><dd>${escapeHtml(ds.title)}</dd>
                <dt>Nature of the data</dt><dd>${escapeHtml(STATUS_LABELS[ds.dataset_status] || ds.dataset_status)}</dd>
                ${ds.snapshot_date ? `<dt>Source snapshot</dt><dd>${escapeHtml(String(ds.snapshot_date).slice(0, 19).replace('T', ' '))}</dd>` : ''}
                <dt>Import / mapping version</dt><dd>${escapeHtml(ds.import_version)} / ${escapeHtml(ds.mapping_version)}</dd>
                ${ds.landing_page ? `<dt>Source platform</dt><dd><a href="${escapeAttr(ds.landing_page)}" target="_blank" rel="noopener">${escapeHtml(ds.landing_page)}</a></dd>` : ''}
                ${ds.license ? `<dt>Licence</dt><dd><a href="${escapeAttr(ds.license)}" target="_blank" rel="noopener">${escapeHtml(ds.license)}</a></dd>` : ''}
                ${process.protocol_version ? `<dt>Protocol version</dt><dd>${escapeHtml(process.protocol_version)}</dd>` : ''}
                ${process.taxonomy_version ? `<dt>Fallacy taxonomy</dt><dd>${escapeHtml(process.taxonomy_version)}</dd>` : ''}
            </dl>
            ${process.disclosure ? `<details style="margin-top:0.6rem;"><summary style="cursor:pointer;font-size:0.9rem;">Disclosure shown to participants</summary><p class="inspect-text" style="font-size:0.9rem;">${escapeHtml(process.disclosure)}</p></details>` : ''}
            <p style="font-size:0.85rem;margin-top:0.6rem;"><a href="${escapeAttr(process.uri)}" target="_blank" rel="noopener"><i class="fas fa-link"></i> Linked-data URI</a> • <a href="${DKG_BASE}/sparql.html" target="_blank" rel="noopener"><i class="fas fa-code"></i> Query with SPARQL on the DKG site</a> • <button type="button" class="link-button" data-inspect="${escapeAttr(process.uri)}">Technical view (all triples)</button></p>
        </div>` : '';

    const detailsHTML = `
        <button class="back-button" onclick="backToResults()"><i class="fas fa-arrow-left"></i> Back to results</button>
        <div class="process-header">
            ${process.platform_logo ? `<div class="process-logo"><img src="${escapeAttr(process.platform_logo)}" alt="${escapeAttr(process.platform_logo_alt || process.platform + ' logo')}"></div>` : ''}
            <div class="process-title">
                <h2 style="margin:0;">${escapeHtml(process.title || 'Untitled Process')}</h2>
                <div class="process-badges">
                    <span class="badge badge-type"><i class="fas fa-globe" aria-hidden="true"></i> ${escapeHtml(process.platform || 'Unknown')}</span>
                    ${process.dataset_status ? `<span class="badge badge-status">${escapeHtml(STATUS_LABELS[process.dataset_status] || process.dataset_status)}</span>` : ''}
                    ${process.language ? `<span class="badge badge-condition"><i class="fas fa-language" aria-hidden="true"></i> ${escapeHtml(process.language)}</span>` : ''}
                    ${process.start_date || process.date ? `<span class="badge badge-condition"><i class="fas fa-calendar" aria-hidden="true"></i> ${escapeHtml(process.start_date || formatDate(process.date))}${process.end_date && process.end_date !== process.start_date ? ' – ' + escapeHtml(process.end_date) : ''}</span>` : ''}
                </div>
                <div class="result-meta">
                    <span><i class="fas fa-link"></i> <a href="${escapeAttr(process.uri)}" target="_blank" rel="noopener">URI</a></span>
                    ${process.url ? `<span><i class="fas fa-external-link-alt"></i> <a href="${escapeAttr(process.url)}" target="_blank" rel="noopener">Source platform</a></span>` : ''}
                </div>
            </div>
        </div>
        ${statusNote}
        <p style="margin-top:1rem;line-height:1.65;">${escapeHtml(process.description || 'No description available')}</p>
        <div class="stat-tiles">${tiles.map(([l, n]) => `<div class="stat-tile"><div class="n">${fmtNum(n)}</div><div class="l">${escapeHtml(l)}</div></div>`).join('')}</div>
        ${conditionHtml}${stanceHtml}
        ${topicsHtml}
        ${legalHtml}

        <div class="section" id="contributions-section">
            <h3><i class="fas fa-comments"></i> Contributions <span id="contrib-count-label">(${fmtNum(contribState.total)})</span></h3>
            <div class="contrib-toolbar">
                ${s.by_kind && Object.keys(s.by_kind).length > 1 ? `<label>Kind <select id="contribKind"><option value="">All</option>${Object.entries(s.by_kind).map(([k, v]) => `<option value="${escapeAttr(k)}">${escapeHtml(KIND_LABELS[k] || k)} (${v})</option>`).join('')}</select></label>` : ''}
                ${s.by_condition && Object.keys(s.by_condition).length > 1 ? `<label>Condition <select id="contribCondition"><option value="">All</option>${Object.entries(s.by_condition).map(([k, v]) => `<option value="${escapeAttr(k)}">${escapeHtml(CONDITION_LABELS[k] || k)} (${v})</option>`).join('')}</select></label>` : ''}
                <label>Order <select id="contribOrder"><option value="asc">Oldest first</option><option value="desc">Newest first</option></select></label>
                <label>Per page <select id="contribLimit"><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label>
            </div>
            <p class="filters-help" id="contrib-no-text-note" hidden></p>
            <div id="contributions-container">
                <div class="contributions-grid" id="contributions-grid" aria-live="polite"><div class="loading"><div class="spinner"></div></div></div>
                <div id="contributions-pagination"></div>
            </div>
        </div>

        ${(process.fallacies || []).length ? `<div class="section"><h3><i class="fas fa-exclamation-triangle"></i> Detected Fallacies (${process.fallacies.length})</h3><div class="fallacies-grid">${renderFallacies(process.fallacies)}</div></div>` : ''}

        <div class="section">
            <h3><i class="fas fa-users"></i> Participants (${process.participants ? process.participants.length : (s.participants_declared || 0)})</h3>
            <div id="participants-container">
                <div class="participants-grid" id="participants-grid">${renderParticipants(process.participants || [], 1)}</div>
                <div id="participants-pagination"></div>
            </div>
        </div>

        ${linksHtml}
        ${metricsHtml}
        ${provenanceHtml}

        <div class="section">
            <h3><i class="fas fa-project-diagram"></i> Graph Visualization</h3>
            <p class="filters-help">Process, the contributions shown on the current page, their authors and reply relations.</p>
            <div id="graphViz"></div>
        </div>

        <div class="section">
            <h3><i class="fas fa-download"></i> Download This Deliberation</h3>
            <div class="download-options">
                <button onclick="downloadProcess('${escapeAttr(process.uri)}', 'ttl')" class="btn-secondary"><i class="fas fa-file-code"></i> RDF/Turtle</button>
                <button onclick="downloadProcess('${escapeAttr(process.uri)}', 'jsonld')" class="btn-secondary"><i class="fas fa-file-code"></i> JSON-LD</button>
                <button onclick="downloadProcess('${escapeAttr(process.uri)}', 'json')" class="btn-secondary"><i class="fas fa-file-alt"></i> JSON</button>
            </div>
        </div>`;

    detailsContainer.innerHTML = detailsHTML;
    bindInspectButtons(detailsContainer);
    detailsContainer.querySelectorAll('.topic-chip').forEach(chip => chip.addEventListener('click', () => {
        detailsContainer.querySelectorAll('.topic-chip').forEach(c => c.classList.remove('active'));
        chip.classList.add('active');
        contribState.topic = chip.dataset.topic; contribState.offset = 0; loadContributions();
    }));
    ['contribKind', 'contribCondition', 'contribOrder', 'contribLimit'].forEach(id => {
        const el = document.getElementById(id);
        if (!el) return;
        el.addEventListener('change', () => {
            contribState.kind = (document.getElementById('contribKind') || {}).value || '';
            contribState.condition = (document.getElementById('contribCondition') || {}).value || '';
            contribState.order = (document.getElementById('contribOrder') || {}).value || 'asc';
            contribState.limit = parseInt((document.getElementById('contribLimit') || {}).value || '10');
            contribState.offset = 0;
            loadContributions();
        });
    });
    window.scrollTo({ top: detailsContainer.offsetTop - 20, behavior: 'smooth' });
    loadContributions();
}

function linkItem(l) {
    const type = l.link_type || 'explicit';
    const other = l.other ? `<button type="button" class="link-button" data-inspect="${escapeAttr(l.other.uri)}">${escapeHtml(truncate(l.other.label, 90))}</button>${l.other_platform ? ` <span style="color:var(--text-light)">(${escapeHtml(l.other_platform)})</span>` : ''}` : escapeHtml(l.label || '');
    return `<li>
        <span class="badge badge-link-${escapeAttr(type)}">${escapeHtml(type)}</span>
        <span class="badge badge-condition">${escapeHtml((l.relation || '').replace(/_/g, ' '))}</span>
        <span>${other}</span>
        ${l.similarity != null ? `<span class="score" title="Similarity score (${escapeAttr(l.method || '')})">score ${Number(l.similarity).toFixed(3)}</span>` : ''}
        ${l.uri ? `<button type="button" class="link-button" data-inspect="${escapeAttr(l.uri)}" style="font-size:0.8rem;">details</button>` : ''}
    </li>`;
}

// ---------------------------------------------------------------------------
// Contributions (server-side pagination)
// ---------------------------------------------------------------------------
async function loadContributions() {
    const grid = document.getElementById('contributions-grid');
    const pag = document.getElementById('contributions-pagination');
    if (!grid) return;
    grid.innerHTML = '<div class="loading"><div class="spinner"></div></div>';
    const params = new URLSearchParams({ uri: contribState.uri, offset: contribState.offset, limit: contribState.limit, order: contribState.order });
    if (contribState.kind) params.set('kind', contribState.kind);
    if (contribState.condition) params.set('condition', contribState.condition);
    if (contribState.topic) params.set('topic', contribState.topic);
    try {
        const response = await fetch(`${API_BASE}/process/contributions?${params.toString()}`);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        contribState.total = data.total;
        const label = document.getElementById('contrib-count-label');
        const unfiltered = !contribState.kind && !contribState.condition && !contribState.topic;
        const withoutText = unfiltered && contribState.totalAll > data.total ? contribState.totalAll - data.total : 0;
        if (label) label.textContent = withoutText ? `(${fmtNum(data.total)} with text, of ${fmtNum(contribState.totalAll)})` : `(${fmtNum(data.total)})`;
        const note = document.getElementById('contrib-no-text-note');
        if (note) note.hidden = !withoutText;
        if (note && withoutText) note.textContent = `${fmtNum(withoutText)} contributions have no text in the source data (for example feedback submitted only as an attachment). They are counted in the statistics but cannot be listed.`;
        if (!data.contributions.length) {
            grid.innerHTML = '<p class="empty-state">No contributions match the current filters.</p>';
            pag.innerHTML = '';
        } else {
            grid.innerHTML = data.contributions.map(contributionCard).join('');
            bindInspectButtons(grid);
            grid.querySelectorAll('.contribution-card').forEach(card => {
                card.addEventListener('click', () => showResourceDetails(card.dataset.uri));
                card.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); showResourceDetails(card.dataset.uri); } });
            });
            renderServerPagination(pag, data.total, contribState.offset, contribState.limit);
        }
        if (currentProcess) visualizeGraph({ ...currentProcess, contributions: data.contributions.map(c => ({ uri: c.uri, author: c.author ? c.author.name : 'Unknown', responseTo: c.responseTo, text: c.text })) });
    } catch (error) {
        console.error('Error loading contributions:', error);
        grid.innerHTML = '<p class="error-state"><i class="fas fa-exclamation-circle"></i> Unable to load contributions.</p>';
    }
}

function contributionCard(c) {
    const ann = c.annotations || {};
    const badges = [];
    if (c.kind && c.kind !== 'comment') badges.push(`<span class="badge badge-type">${escapeHtml(KIND_LABELS[c.kind] || c.kind)}</span>`);
    if (c.source === 'seed') badges.push(`<span class="badge badge-status">Seed (process design)</span>`);
    if (c.condition) badges.push(`<span class="badge badge-condition">${escapeHtml(CONDITION_LABELS[c.condition] || c.condition)}</span>`);
    if (c.stance) badges.push(`<span class="badge badge-stance-${escapeAttr(c.stance)}" title="method: ${escapeAttr(c.stance_method || '')}">stance: ${escapeHtml(STANCE_LABELS[c.stance] || c.stance)}${c.stance_method === 'seed_ground_truth' ? ' (ground truth)' : ' (model)'}</span>`);
    if (c.proposed_operation) badges.push(`<span class="badge badge-human">proposal: ${escapeHtml(c.proposed_operation)}</span>`);
    const foot = [];
    if (ann.ai_feedback) foot.push(`<span class="pill"><i class="fas fa-robot" aria-hidden="true"></i> AI feedback</span>`);
    if (c.fallacy_labels && c.fallacy_labels.length) foot.push(`<span class="pill"><i class="fas fa-flag" aria-hidden="true"></i> label: ${escapeHtml(c.fallacy_labels.join(', '))}</span>`);
    if (ann.peer_evaluations) foot.push(`<span class="pill"><i class="fas fa-users" aria-hidden="true"></i> ${ann.peer_evaluations} peer evaluation${ann.peer_evaluations > 1 ? 's' : ''}</span>`);
    if (ann.responses) foot.push(`<span class="pill"><i class="fas fa-reply" aria-hidden="true"></i> ${ann.responses} recorded response${ann.responses > 1 ? 's' : ''}</span>`);
    (c.anchors || []).forEach(a => foot.push(`<span class="pill" title="${escapeAttr(a.text || '')}"><i class="fas fa-anchor" aria-hidden="true"></i> ${a.method === 'system_prediction' ? 'system' : 'user'}: ${escapeHtml(truncate(a.provision, 40))}${a.confidence != null ? ` (${Number(a.confidence).toFixed(2)})` : ''}</span>`));
    if (c.topic && c.topic.label) foot.push(`<span class="pill"><i class="fas fa-tag" aria-hidden="true"></i> ${escapeHtml(truncate(c.topic.label, 40))}</span>`);
    return `
        <div class="contribution-card clickable-contribution" role="button" tabindex="0" data-uri="${escapeAttr(c.uri)}">
            <div class="contrib-head">
                <strong>${escapeHtml(c.author ? c.author.name : 'Unknown')}</strong>
                ${c.timestamp ? `<span>• ${escapeHtml(formatDate(c.timestamp))}</span>` : ''}
                ${c.language ? `<span>• ${escapeHtml(c.language)}</span>` : ''}
                ${badges.join(' ')}
            </div>
            ${c.responseTo ? `<div class="parent-quote"><i class="fas fa-reply" aria-hidden="true"></i> ${c.relation ? escapeHtml(c.relation) + 's with' : 'replies to'}: “${escapeHtml(truncate(c.responseTo_label || '', 110))}”</div>` : ''}
            <p class="contrib-text">${escapeHtml(truncate(c.text || '', 700))}</p>
            ${foot.length ? `<div class="contrib-foot">${foot.join('')}</div>` : ''}
            <p style="font-size: 0.8rem; color: var(--text-light); margin-top: 0.5rem;"><i class="fas fa-search-plus"></i> Open to inspect text, metadata, annotations and provenance</p>
        </div>`;
}

function renderServerPagination(container, total, offset, limit) {
    const totalPages = Math.ceil(total / limit);
    const currentPage = Math.floor(offset / limit) + 1;
    if (totalPages <= 1) { container.innerHTML = ''; return; }
    let html = '<nav class="pagination" aria-label="Contributions pagination">';
    const btn = (page, label, active) => `<button class="pagination-btn ${active ? 'active' : ''}" data-page="${page}" ${active ? 'aria-current="page"' : ''}>${label}</button>`;
    if (currentPage > 1) html += btn(currentPage - 1, '<i class="fas fa-chevron-left"></i> Previous');
    const maxButtons = 5;
    let startPage = Math.max(1, currentPage - Math.floor(maxButtons / 2));
    let endPage = Math.min(totalPages, startPage + maxButtons - 1);
    if (endPage - startPage < maxButtons - 1) startPage = Math.max(1, endPage - maxButtons + 1);
    if (startPage > 1) { html += btn(1, '1'); if (startPage > 2) html += '<span class="pagination-ellipsis">...</span>'; }
    for (let i = startPage; i <= endPage; i++) html += btn(i, String(i), i === currentPage);
    if (endPage < totalPages) { if (endPage < totalPages - 1) html += '<span class="pagination-ellipsis">...</span>'; html += btn(totalPages, String(totalPages)); }
    if (currentPage < totalPages) html += btn(currentPage + 1, 'Next <i class="fas fa-chevron-right"></i>');
    html += '</nav>';
    container.innerHTML = html;
    container.querySelectorAll('[data-page]').forEach(b => b.addEventListener('click', () => {
        contribState.offset = (parseInt(b.dataset.page) - 1) * contribState.limit;
        loadContributions();
        document.getElementById('contributions-section').scrollIntoView({ behavior: 'smooth', block: 'start' });
    }));
}

// Render fallacies (legacy fallacy nodes of other platforms)
function renderFallacies(fallacies) {
    if (!fallacies || fallacies.length === 0) return '<p style="color: var(--text-light);">No fallacies detected</p>';
    return fallacies.map(f => `
        <div class="fallacy-card">
            <p><strong>Type:</strong> ${escapeHtml(getFallacyName(f.type))}</p>
            <p><strong>Location:</strong> ${escapeHtml(f.location || 'N/A')}</p>
        </div>`).join('');
}

// Participants (legacy list from /api/process)
const PARTICIPANTS_PER_PAGE = 10;
function renderParticipants(participants, page = 1) {
    currentParticipantsPage = page;
    if (!participants || participants.length === 0) {
        setTimeout(() => renderParticipantsPagination(0, 1), 0);
        return '<p style="color: var(--text-light);">No participant list available for this process.</p>';
    }
    const start = (page - 1) * PARTICIPANTS_PER_PAGE;
    const pageParticipants = participants.slice(start, start + PARTICIPANTS_PER_PAGE);
    const html = pageParticipants.map(p => `
        <div class="participant-card" role="button" tabindex="0" data-inspect="${escapeAttr(p.uri)}" style="cursor: pointer;">
            <p><strong>${escapeHtml(p.name || 'Unknown')}</strong></p>
            ${p.party ? `<p>Party: ${escapeHtml(p.party)}</p>` : ''}
            <p style="font-size: 0.8rem; color: var(--text-light); margin-top: 0.5rem;"><i class="fas fa-link"></i> Click to view details</p>
        </div>`).join('');
    setTimeout(() => { renderParticipantsPagination(participants.length, page); const g = document.getElementById('participants-grid'); if (g) bindInspectButtons(g); }, 0);
    return html;
}

function renderParticipantsPagination(totalParticipants, currentPage) {
    const paginationContainer = document.getElementById('participants-pagination');
    if (!paginationContainer) return;
    const totalPages = Math.ceil(totalParticipants / PARTICIPANTS_PER_PAGE);
    if (totalPages <= 1) { paginationContainer.innerHTML = ''; return; }
    let html = '<div class="pagination">';
    if (currentPage > 1) html += `<button class="pagination-btn" onclick="changeParticipantsPage(${currentPage - 1})"><i class="fas fa-chevron-left"></i> Previous</button>`;
    const maxButtons = 5;
    let startPage = Math.max(1, currentPage - Math.floor(maxButtons / 2));
    let endPage = Math.min(totalPages, startPage + maxButtons - 1);
    if (endPage - startPage < maxButtons - 1) startPage = Math.max(1, endPage - maxButtons + 1);
    if (startPage > 1) { html += `<button class="pagination-btn" onclick="changeParticipantsPage(1)">1</button>`; if (startPage > 2) html += '<span class="pagination-ellipsis">...</span>'; }
    for (let i = startPage; i <= endPage; i++) html += `<button class="pagination-btn ${i === currentPage ? 'active' : ''}" onclick="changeParticipantsPage(${i})">${i}</button>`;
    if (endPage < totalPages) { if (endPage < totalPages - 1) html += '<span class="pagination-ellipsis">...</span>'; html += `<button class="pagination-btn" onclick="changeParticipantsPage(${totalPages})">${totalPages}</button>`; }
    if (currentPage < totalPages) html += `<button class="pagination-btn" onclick="changeParticipantsPage(${currentPage + 1})">Next <i class="fas fa-chevron-right"></i></button>`;
    html += '</div>';
    paginationContainer.innerHTML = html;
}

function changeParticipantsPage(page) {
    const grid = document.getElementById('participants-grid');
    if (!grid) return;
    grid.innerHTML = renderParticipants(currentParticipants, page);
    document.getElementById('participants-container').scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ---------------------------------------------------------------------------
// Graph visualisation (D3)
// ---------------------------------------------------------------------------
function visualizeGraph(process) {
    const container = document.getElementById('graphViz');
    if (!container || typeof d3 === 'undefined') return;
    container.innerHTML = '';
    const nodes = [{ id: process.uri, label: truncate(process.title || 'Process', 40), type: 'process', uri: process.uri }];
    const links = [];
    const participantsMap = new Map();
    const contributionUriToId = new Map();
    (process.contributions || []).forEach((c, i) => {
        const nodeId = `contribution_${i}`;
        contributionUriToId.set(c.uri, nodeId);
        const isComment = !!c.responseTo;
        nodes.push({ id: nodeId, label: isComment ? `Reply ${i + 1}` : `Contribution ${i + 1}`, type: isComment ? 'comment' : 'contribution', uri: c.uri });
        if (!isComment) links.push({ source: process.uri, target: nodeId });
        if (c.author && c.author !== 'Unknown') participantsMap.set(c.author, nodeId);
    });
    (process.contributions || []).forEach((c) => {
        if (c.responseTo) {
            const commentId = contributionUriToId.get(c.uri);
            const parentId = contributionUriToId.get(c.responseTo);
            if (commentId && parentId) links.push({ source: parentId, target: commentId, type: 'responseTo' });
            else if (commentId) links.push({ source: process.uri, target: commentId, type: 'responseTo' });
        }
    });
    let participantIndex = 0;
    participantsMap.forEach((contributionId, participantName) => {
        const participantId = `participant_${participantIndex++}`;
        nodes.push({ id: participantId, label: participantName.length > 30 ? participantName.substr(0, 30) + '...' : participantName, type: 'participant', uri: null });
        links.push({ source: contributionId, target: participantId });
    });
    const width = Math.max(280, Math.min(container.clientWidth || 600, window.innerWidth - 32));
    const height = 500;
    const svg = d3.select('#graphViz').append('svg').attr('viewBox', `0 0 ${width} ${height}`).attr('width', '100%').attr('height', height).style('max-width', '100%').attr('role', 'img').attr('aria-label', 'Force-directed graph of the process and the contributions on this page');
    const simulation = d3.forceSimulation(nodes)
        .force('link', d3.forceLink(links).id(d => d.id).distance(90))
        .force('charge', d3.forceManyBody().strength(-250))
        .force('center', d3.forceCenter(width / 2, height / 2));
    const link = svg.append('g').selectAll('line').data(links).enter().append('line')
        .attr('stroke', d => d.type === 'responseTo' ? '#f59e0b' : '#999')
        .attr('stroke-width', d => d.type === 'responseTo' ? 2.5 : 2)
        .attr('stroke-dasharray', d => d.type === 'responseTo' ? '5,5' : '0');
    const node = svg.append('g').selectAll('circle').data(nodes).enter().append('circle')
        .attr('r', d => d.type === 'process' ? 15 : d.type === 'participant' ? 10 : 8)
        .attr('fill', d => d.type === 'process' ? '#4a9d3c' : d.type === 'participant' ? '#ffd700' : d.type === 'comment' ? '#f59e0b' : '#10b981')
        .style('cursor', 'pointer')
        .on('click', function (event, d) { event.stopPropagation(); if (d.uri) showResourceDetails(d.uri); })
        .call(d3.drag().on('start', dragstarted).on('drag', dragged).on('end', dragended));
    const label = svg.append('g').selectAll('text').data(nodes).enter().append('text').text(d => d.label).attr('font-size', 10).attr('dx', 12).attr('dy', 4);
    simulation.on('tick', () => {
        link.attr('x1', d => d.source.x).attr('y1', d => d.source.y).attr('x2', d => d.target.x).attr('y2', d => d.target.y);
        node.attr('cx', d => d.x).attr('cy', d => d.y);
        label.attr('x', d => d.x).attr('y', d => d.y);
    });
    function dragstarted(event, d) { if (!event.active) simulation.alphaTarget(0.3).restart(); d.fx = d.x; d.fy = d.y; }
    function dragged(event, d) { d.fx = event.x; d.fy = event.y; }
    function dragended(event, d) { if (!event.active) simulation.alphaTarget(0); d.fx = null; d.fy = null; }
}

function backToResults() {
    document.getElementById('searchResults').style.display = 'block';
    document.getElementById('processDetails').style.display = 'none';
    const params = new URLSearchParams(window.location.search);
    if (params.get('process')) pushUrl({ q: document.getElementById('searchInput').value.trim() || null });
}

// ---------------------------------------------------------------------------
// Autocomplete
// ---------------------------------------------------------------------------
let autocompleteTimeout;
async function handleAutocomplete() {
    clearTimeout(autocompleteTimeout);
    const query = document.getElementById('searchInput').value.trim();
    const autocompleteDiv = document.getElementById('autocomplete');
    if (query.length < 2) { autocompleteDiv.classList.remove('show'); return; }
    autocompleteTimeout = setTimeout(async () => {
        try {
            const response = await fetch(`${API_BASE}/autocomplete?q=${encodeURIComponent(query)}`);
            const data = await response.json();
            if (data.suggestions && data.suggestions.length > 0) {
                autocompleteDiv.innerHTML = data.suggestions.map(s => `<div class="autocomplete-item" role="option" tabindex="0" data-s="${escapeAttr(s)}">${escapeHtml(s)}</div>`).join('');
                autocompleteDiv.querySelectorAll('.autocomplete-item').forEach(it => {
                    it.addEventListener('click', () => selectSuggestion(it.dataset.s));
                    it.addEventListener('keydown', (e) => { if (e.key === 'Enter') selectSuggestion(it.dataset.s); });
                });
                autocompleteDiv.classList.add('show');
            } else autocompleteDiv.classList.remove('show');
        } catch (error) { console.error('Autocomplete error:', error); }
    }, 300);
}

function selectSuggestion(suggestion) {
    document.getElementById('searchInput').value = suggestion;
    document.getElementById('autocomplete').classList.remove('show');
    performSearch();
}

// ---------------------------------------------------------------------------
// Downloads
// ---------------------------------------------------------------------------
async function downloadData(format) {
    try {
        const response = await fetch(`${API_BASE}/download/${format}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ full_dump: true }) });
        if (format === 'json') { const data = await response.json(); downloadJSON(data, `dkg_export_${new Date().toISOString().split('T')[0]}.json`); }
        else { const blob = await response.blob(); const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `dkg_export_${new Date().toISOString().split('T')[0]}.${format}`; a.click(); }
    } catch (error) { console.error('Download error:', error); alert('Download error. Please try again.'); }
}

async function downloadProcess(uri, format) {
    try {
        const response = await fetch(`${API_BASE}/download/process/${format}?uri=${encodeURIComponent(uri)}`);
        const processId = uri.split('/').pop();
        if (format === 'json') { const data = await response.json(); downloadJSON(data, `process_${processId}_${new Date().toISOString().split('T')[0]}.json`); }
        else { const blob = await response.blob(); const url_obj = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url_obj; a.download = `process_${processId}.${format}`; a.click(); window.URL.revokeObjectURL(url_obj); }
    } catch (error) { console.error('Download error:', error); alert('Download error. Please try again.'); }
}

function downloadJSON(data, filename) {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
}

// ---------------------------------------------------------------------------
// UI helpers
// ---------------------------------------------------------------------------
function showLoading() { document.getElementById('searchResults').innerHTML = '<div class="loading" role="status" aria-label="Loading"><div class="spinner"></div></div>'; }
function showError(message) { document.getElementById('searchResults').innerHTML = `<div class="error-state" role="alert"><i class="fas fa-exclamation-circle" style="font-size: 3rem; margin-bottom: 1rem;"></i><h3>${escapeHtml(message)}</h3></div>`; }
function emptyState(title, hint) { return `<div class="empty-state"><i class="fas fa-search" style="font-size: 3rem; margin-bottom: 1rem;"></i><h3>${escapeHtml(title)}</h3><p>${escapeHtml(hint)}</p></div>`; }
function escapeHtml(text) { const div = document.createElement('div'); div.textContent = text == null ? '' : String(text); return div.innerHTML; }
function escapeAttr(text) { return escapeHtml(text).replace(/"/g, '&quot;').replace(/'/g, '&#39;'); }
function truncate(text, maxLength) { text = text == null ? '' : String(text); return text.length <= maxLength ? text : text.substr(0, maxLength) + '...'; }
function fmtNum(n) { return (n == null || isNaN(n)) ? '0' : Number(n).toLocaleString('en-US'); }
function fmtMetric(v) { const n = Number(v); return isNaN(n) ? String(v) : (Number.isInteger(n) ? String(n) : n.toFixed(3)); }
function getFallacyName(uri) { if (!uri) return 'Unknown'; const name = uri.split('#').pop().split('/').pop(); return name.replace(/_/g, ' ').replace(/([A-Z])/g, ' $1').trim(); }
function formatDate(dateString) {
    if (!dateString) return 'N/A';
    try {
        let date;
        if (dateString.includes('T')) date = new Date(dateString);
        else if (dateString.match(/^\d{4}-\d{2}-\d{2}$/)) date = new Date(dateString);
        else if (dateString.includes('/')) date = new Date(dateString.split(/[\s\/]/)[0]);
        else return dateString;
        if (isNaN(date.getTime())) return dateString;
        return date.toISOString().split('T')[0];
    } catch (e) { return dateString; }
}

// ---------------------------------------------------------------------------
// Resource inspection modal (type-aware)
// ---------------------------------------------------------------------------
async function showResourceDetails(uri, skipUrl) {
    const modal = document.getElementById('resourceModal');
    const modalTitle = document.getElementById('modalTitle');
    const modalBody = document.getElementById('modalBody');
    lastFocusedElement = document.activeElement;
    modalBody.innerHTML = '<div class="loading" role="status"><div class="spinner"></div></div>';
    modalTitle.textContent = 'Resource details';
    modal.style.display = 'flex';
    modal.querySelector('.modal-content').focus();
    if (!skipUrl) { const url = new URL(window.location.href); url.searchParams.set('show_resource', uri); window.history.replaceState({}, document.title, url.toString()); }
    try {
        const response = await fetch(`${API_BASE}/resource/inspect?uri=${encodeURIComponent(uri)}`);
        const resource = await response.json();
        if (!response.ok || resource.error) {
            modalBody.innerHTML = `<p class="error-state" role="alert">${escapeHtml(resource.error === 'Resource not found' ? 'This resource does not exist in the knowledge graph (it may have been removed or the link is outdated).' : (resource.error || 'Error loading resource'))}</p>`;
            return;
        }
        renderInspection(resource);
    } catch (error) {
        modalBody.innerHTML = `<p class="error-state" role="alert">Error loading resource: ${escapeHtml(error.message)}</p>`;
    }
}

function closeResourceModal() {
    document.getElementById('resourceModal').style.display = 'none';
    const url = new URL(window.location.href);
    if (url.searchParams.has('show_resource')) { url.searchParams.delete('show_resource'); window.history.replaceState({}, document.title, url.toString()); }
    if (lastFocusedElement && lastFocusedElement.focus) lastFocusedElement.focus();
}

function originBadge(origin) {
    if (origin === 'automated') return '<span class="badge badge-ai"><i class="fas fa-robot" aria-hidden="true"></i> automated</span>';
    if (origin === 'human') return '<span class="badge badge-human"><i class="fas fa-user" aria-hidden="true"></i> human</span>';
    return '<span class="badge badge-condition">unspecified origin</span>';
}

function annotationCard(a) {
    const head = [`<strong>${escapeHtml(TYPE_LABEL_OF(a.kind))}</strong>`, originBadge(a.origin)];
    if (a.model) head.push(`<span class="badge badge-ai">${escapeHtml(a.model)}</span>`);
    if (a.method) head.push(`<span class="badge badge-condition">${escapeHtml(a.method.replace(/_/g, ' '))}</span>`);
    if (a.attributed_to && a.attributed_to.label) head.push(`<span class="badge badge-condition">by ${escapeHtml(a.attributed_to.label)}</span>`);
    if (a.timestamp) head.push(`<span style="color:var(--text-light)">${escapeHtml(formatDateTime(a.timestamp))}</span>`);
    const body = [];
    if (a.fallacy) body.push(`<p><strong>Fallacy category:</strong> <button type="button" class="link-button" data-inspect="${escapeAttr(a.fallacy.uri)}">${escapeHtml(a.fallacy.label)}</button>${a.confidence != null ? ` <span style="color:var(--text-light)">(score ${Number(a.confidence).toFixed(2)} on the method's own scale)</span>` : ''}</p>`);
    else if (a.label && a.kind !== 'AspectAnnotation') body.push(`<p><strong>Label:</strong> ${escapeHtml(a.label)}${a.confidence != null ? ` <span style="color:var(--text-light)">(score ${Number(a.confidence).toFixed(2)})</span>` : ''}</p>`);
    if (a.stance) body.push(`<p><strong>Stance:</strong> <span class="badge badge-stance-${escapeAttr(a.stance)}">${escapeHtml(STANCE_LABELS[a.stance] || a.stance)}</span>${a.confidence != null ? ` <span style="color:var(--text-light)">confidence ${Number(a.confidence).toFixed(2)}</span>` : ''}${a.target ? ` – towards <button type="button" class="link-button" data-inspect="${escapeAttr(a.target.uri)}">${escapeHtml(truncate(a.target.label, 70))}</button>` : ''}</p>`);
    if (a.action) body.push(`<p><strong>Recorded action:</strong> ${escapeHtml(ACTION_LABELS[a.action] || a.action)}${a.corrected_to ? ` → ${escapeHtml(a.corrected_to)}` : ''}${a.action_reason ? ` (${escapeHtml(a.action_reason)})` : ''}${a.responds_to ? ` – on <button type="button" class="link-button" data-inspect="${escapeAttr(a.responds_to.uri)}">${escapeHtml(a.responds_to.label)}</button>` : ''}</p>`);
    if (a.has_problem != null && a.kind === 'PeerEvaluation') body.push(`<p><strong>Peer judgement:</strong> ${a.has_problem ? 'has an argumentation problem' : 'no problem'}</p>`);
    if (a.advice) body.push(`<p><strong>Advice:</strong></p><div class="inspect-text">${escapeHtml(a.advice)}</div>`);
    if (a.rewrite) body.push(`<p><strong>Rewrite suggestion (never applied automatically):</strong></p><div class="inspect-text">${escapeHtml(a.rewrite)}</div>`);
    if (a.reviewed_text) body.push(`<details><summary style="cursor:pointer;">Text that was reviewed</summary><div class="inspect-text">${escapeHtml(a.reviewed_text)}</div></details>`);
    if (a.rationale) body.push(`<p><strong>Rationale:</strong> ${escapeHtml(a.rationale)}</p>`);
    if (a.aspects && a.aspects.length) body.push(`<p>${a.aspects.map(x => `<span class="badge badge-condition">${escapeHtml(x)}</span>`).join(' ')}</p>`);
    if (a.presented_at && a.presented_at.length) body.push(`<p style="color:var(--text-light)">Shown to the participant at ${a.presented_at.map(formatDateTime).map(escapeHtml).join(', ')}</p>`);
    if (a.runs && a.runs.length) body.push(`<details><summary style="cursor:pointer;">Model runs (${a.runs.length})${a.pending_models && a.pending_models.length ? `, pending: ${escapeHtml(a.pending_models.join(', '))}` : ''}${a.response_strategy ? ` – strategy: ${escapeHtml(a.response_strategy)}` : ''}</summary><ul style="font-size:0.85rem;">${a.runs.map(r => `<li>${escapeHtml(r.model)} (${escapeHtml(r.role)}) – ${r.succeeded === false ? 'failed' : 'ok'}${r.latency_ms != null ? `, ${r.latency_ms} ms` : ''}${r.prompt_tokens != null ? `, ${r.prompt_tokens}+${r.completion_tokens || 0} tokens` : ''}${r.labels && r.labels.length ? `, labels: ${escapeHtml(r.labels.join(', '))}` : ''}</li>`).join('')}</ul></details>`);
    if (a.note) body.push(`<p style="color:var(--text-light);font-size:0.85rem;">${escapeHtml(a.note)}</p>`);
    if (a.children && a.children.length) {
        body.push(a.children.map(ch => `<div class="ann-child">${originBadge(ch.origin)} <strong>${escapeHtml(TYPE_LABEL_OF(ch.kind))}</strong>${ch.attributed_to ? ` by ${escapeHtml(ch.attributed_to)}` : ''}${ch.timestamp ? ` <span style="color:var(--text-light)">${escapeHtml(formatDateTime(ch.timestamp))}</span>` : ''}:
            ${ch.fallacy ? ` ${escapeHtml(ch.fallacy)}${ch.confidence != null ? ` (score ${Number(ch.confidence).toFixed(2)})` : ''}` : ''}
            ${ch.action ? ` ${escapeHtml(ACTION_LABELS[ch.action] || ch.action)}${ch.corrected_to ? ' → ' + escapeHtml(ch.corrected_to) : ''}` : ''}
            ${ch.rationale ? `<br><em>${escapeHtml(ch.rationale)}</em>` : ''}
            <button type="button" class="link-button" data-inspect="${escapeAttr(ch.uri)}" style="font-size:0.78rem;">details</button></div>`).join(''));
    }
    return `<div class="annotation-card ${escapeAttr(a.origin)}"><div class="ann-head">${head.join(' ')}<button type="button" class="link-button" data-inspect="${escapeAttr(a.uri)}" style="margin-left:auto;font-size:0.8rem;">open</button></div><div class="ann-body">${body.join('')}</div></div>`;
}

function TYPE_LABEL_OF(kind) {
    return { AIFeedback: 'AI feedback', FallacyAnnotation: 'Fallacy label', StanceAnnotation: 'Stance label', PeerEvaluation: 'Peer evaluation', AnnotationResponse: 'Recorded response', AspectAnnotation: 'Key aspects', ProcessLink: 'Link', Annotation: 'Annotation' }[kind] || kind;
}

function anchorBlock(a) {
    const isSystem = a.method === 'system_prediction';
    return `<div class="annotation-card ${isSystem ? 'automated' : 'human'}">
        <div class="ann-head"><strong>${isSystem ? 'System-resolved anchor' : (a.method === 'user_selection' ? 'Passage selected by the author' : 'Article declared by the author')}</strong> ${isSystem ? originBadge('automated') : originBadge('human')} <span class="badge badge-condition">${escapeHtml(a.kind === 'range' ? 'passage' : 'whole article')}</span>${a.model ? `<span class="badge badge-ai">${escapeHtml(a.model)}</span>` : ''}<button type="button" class="link-button" data-inspect="${escapeAttr(a.uri)}" style="margin-left:auto;font-size:0.8rem;">open</button></div>
        <div class="ann-body">
            ${a.provision ? `<p><strong>Provision:</strong> <button type="button" class="link-button" data-inspect="${escapeAttr(a.provision.uri)}">${escapeHtml(a.provision.label)}</button></p>` : ''}
            ${a.text ? `<div class="inspect-text" style="font-size:0.9rem;">“${escapeHtml(a.text)}”</div>` : ''}
            ${a.expression ? `<p style="font-size:0.85rem;"><strong>Version:</strong> <button type="button" class="link-button" data-inspect="${escapeAttr(a.expression.uri)}">${escapeHtml(truncate(a.expression.label, 80))}</button> <span class="mono">${escapeHtml(a.frbr_expression)}</span></p>` : ''}
            ${isSystem ? `<p style="font-size:0.85rem;"><strong>Method:</strong> ${escapeHtml((a.resolution_method || '').replace(/_/g, ' '))}${a.confidence != null ? `, cosine similarity ${Number(a.confidence).toFixed(3)}` : ''}${a.agrees_with_user != null ? ` – ${a.agrees_with_user ? 'agrees' : 'does not agree'} with the author's anchor` : ''}</p>` : ''}
        </div></div>`;
}

function renderInspection(r) {
    const modalTitle = document.getElementById('modalTitle');
    const modalBody = document.getElementById('modalBody');
    const mainType = (r.types || []).find(t => ['Contribution', 'AIFeedback', 'PeerEvaluation', 'AnnotationResponse', 'FallacyAnnotation', 'StanceAnnotation', 'AspectAnnotation', 'LegalResourceAnchor', 'LegalProvision', 'LegalExpression', 'LegalWork', 'Participant', 'ArtificialAgent', 'Topic', 'DeliberationProcess', 'ProcessLink', 'FallacyType', 'Forum'].includes(t)) || (r.types || [])[0] || 'Resource';
    modalTitle.textContent = `${r.type_labels && r.type_labels.length ? r.type_labels[r.types.indexOf(mainType)] || mainType : mainType}: ${truncate(r.label, 90)}`;
    const s = r.sections || {};
    let html = `<div class="inspect-header">${(r.types || []).map(t => `<span class="badge badge-type">${escapeHtml(t)}</span>`).join(' ')}${r.platform ? `<span class="badge badge-condition"><i class="fas fa-globe" aria-hidden="true"></i> ${escapeHtml(r.platform)}</span>` : ''}${r.process && r.process.uri !== r.uri ? `<button type="button" class="link-button" data-process="${escapeAttr(r.process.uri)}"><i class="fas fa-folder-open" aria-hidden="true"></i> ${escapeHtml(truncate(r.process.label, 60))}</button>` : ''}</div>`;

    if (s.contribution) {
        const c = s.contribution;
        html += `<div class="inspect-section"><h4><i class="fas fa-comment"></i> Participant text</h4>
            <div class="inspect-kv"><dt>Author</dt><dd>${c.author ? `<button type="button" class="link-button" data-inspect="${escapeAttr(c.author.uri)}">${escapeHtml(c.author.name)}</button>${c.author.type ? ` <span class="badge badge-condition">${escapeHtml(c.author.type.replace(/_/g, ' ').toLowerCase())}</span>` : ''}` : 'Unknown'}</dd>
            ${c.timestamp ? `<dt>Date</dt><dd>${escapeHtml(formatDateTime(c.timestamp))}</dd>` : ''}
            ${c.language ? `<dt>Language</dt><dd>${escapeHtml(c.language)}</dd>` : ''}
            ${c.kind ? `<dt>Kind</dt><dd>${escapeHtml(KIND_LABELS[c.kind] || c.kind)}${c.relation ? ` (${escapeHtml(c.relation)}s with the parent)` : ''}</dd>` : ''}
            ${c.source ? `<dt>Source</dt><dd>${escapeHtml(c.source === 'seed' ? 'seed comment provided by the process design' : c.source.replace(/_/g, ' '))}</dd>` : ''}
            ${c.condition ? `<dt>Condition</dt><dd>${escapeHtml(CONDITION_LABELS[c.condition] || c.condition)}</dd>` : ''}
            ${c.topic ? `<dt>Topic</dt><dd><button type="button" class="link-button" data-inspect="${escapeAttr(c.topic.uri)}">${escapeHtml(c.topic.label)}</button></dd>` : ''}
            ${c.word_count != null ? `<dt>Word count</dt><dd>${escapeHtml(c.word_count)}</dd>` : ''}
            </div>
            ${c.parent ? `<div class="parent-quote" style="margin-top:0.6rem;"><i class="fas fa-reply" aria-hidden="true"></i> In reply to ${c.parent.author ? escapeHtml(c.parent.author.name) : 'a comment'}${c.parent.source === 'seed' ? ' (seed comment)' : ''}: “${escapeHtml(truncate(c.parent.text, 220))}” <button type="button" class="link-button" data-inspect="${escapeAttr(c.parent.uri)}">open</button></div>` : ''}
            <div class="inspect-text" style="margin-top:0.6rem;">${escapeHtml(c.text)}</div>
            ${c.draft_text && c.draft_text !== c.text ? `<details style="margin-top:0.5rem;"><summary style="cursor:pointer;">Draft before review (differs from the submitted text)</summary><div class="inspect-text">${escapeHtml(c.draft_text)}</div></details>` : (c.draft_text ? '<p style="font-size:0.82rem;color:var(--text-light);">The draft submitted for review is identical to the final text.</p>' : '')}
            ${c.proposed_operation || c.proposes_change_to.length ? `<div class="notice notice-info" style="margin:0.75rem 0 0;"><strong>Proposal recorded by the platform:</strong> ${escapeHtml(c.proposed_operation || 'change')}${c.proposes_change_to.length ? ` to ${c.proposes_change_to.map(p => `<button type="button" class="link-button" data-inspect="${escapeAttr(p.uri)}">${escapeHtml(p.label)}</button>`).join(', ')}` : ''}. The stance label below is independent from the proposed operation.</div>` : ''}
            ${c.about_provision.length ? `<p style="margin-top:0.6rem;font-size:0.9rem;"><strong>Opinion about:</strong> ${c.about_provision.map(p => `<button type="button" class="link-button" data-inspect="${escapeAttr(p.uri)}">${escapeHtml(p.label)}</button>`).join(', ')}</p>` : ''}
            ${c.references && c.references.length ? `<p style="font-size:0.9rem;"><strong>Refers to document:</strong> ${c.references.map(p => `<button type="button" class="link-button" data-inspect="${escapeAttr(p.uri)}">${escapeHtml(truncate(p.label, 90))}</button>`).join(', ')}</p>` : ''}
            </div>`;
        if (c.anchor_details && c.anchor_details.length) html += `<div class="inspect-section"><h4><i class="fas fa-anchor"></i> Anchors to the legislative text (${c.anchor_details.length})</h4><p class="filters-help">Anchors point to a specific version of the text. The author's anchor and the system's prediction are kept separate.</p>${c.anchor_details.map(anchorBlock).join('')}</div>`;
        if (c.annotation_details && c.annotation_details.length) html += `<div class="inspect-section"><h4><i class="fas fa-tags"></i> Annotations, feedback and evaluations (${c.annotation_details.length})</h4><p class="filters-help">Automated annotations (orange) are model outputs; human annotations (green) come from participants or the research team. Scores are reported on each method's own scale and are not measures of correctness.</p>${c.annotation_details.map(annotationCard).join('')}</div>`;
        if (c.replies && c.replies.length) html += `<div class="inspect-section"><h4><i class="fas fa-reply"></i> Replies (${c.replies.length})</h4>${c.replies.map(rp => `<div class="annotation-card human"><div class="ann-head"><strong>${escapeHtml(rp.author ? rp.author.name : 'Unknown')}</strong>${rp.relation ? `<span class="badge badge-condition">${escapeHtml(rp.relation)}s</span>` : ''}<button type="button" class="link-button" data-inspect="${escapeAttr(rp.uri)}" style="margin-left:auto;font-size:0.8rem;">open</button></div><div class="ann-body">${escapeHtml(rp.text)}</div></div>`).join('')}</div>`;
    }
    if (s.annotation) {
        const a = s.annotation;
        html += `<div class="inspect-section"><h4><i class="fas fa-tag"></i> ${escapeHtml(TYPE_LABEL_OF(a.kind))}</h4>${annotationCard(a)}${a.annotates ? `<p style="font-size:0.9rem;"><strong>About:</strong> <button type="button" class="link-button" data-inspect="${escapeAttr(a.annotates.uri)}">${escapeHtml(a.annotates.types.includes('Contribution') ? 'contribution' : a.annotates.label)}</button>${a.annotates.text ? ` – “${escapeHtml(truncate(a.annotates.text, 200))}”` : ''}</p>` : ''}</div>`;
    }
    if (s.anchor) {
        html += `<div class="inspect-section"><h4><i class="fas fa-anchor"></i> Anchor</h4>${anchorBlock(s.anchor)}${s.anchor.contribution && s.anchor.contribution.length ? `<p style="font-size:0.9rem;"><strong>Contribution:</strong> ${s.anchor.contribution.map(c => `<button type="button" class="link-button" data-inspect="${escapeAttr(c.uri)}">${escapeHtml(c.label)}</button>`).join(', ')}</p>` : ''}</div>`;
    }
    if (s.provision) {
        const p = s.provision;
        html += `<div class="inspect-section"><h4><i class="fas fa-gavel"></i> Legal provision</h4>
            <div class="inspect-kv">${p.eId ? `<dt>Akoma Ntoso eId</dt><dd class="mono">${escapeHtml(p.eId)}</dd>` : ''}${p.segment_index != null ? `<dt>Segment</dt><dd>${escapeHtml(p.segment_index)}</dd>` : ''}${p.expression ? `<dt>Document version</dt><dd><button type="button" class="link-button" data-inspect="${escapeAttr(p.expression.uri)}">${escapeHtml(truncate(p.expression.label, 90))}</button><br><span class="mono">${escapeHtml(p.frbr_expression)}</span></dd>` : ''}${p.work ? `<dt>Work</dt><dd><span class="mono">${escapeHtml(p.frbr_work)}</span></dd>` : ''}</div>
            <div class="inspect-text" lang="it" style="margin-top:0.6rem;">${escapeHtml(p.text)}</div>
            ${p.aspects && p.aspects.length ? `<p style="margin-top:0.6rem;"><strong>Key aspects (automatic):</strong> ${p.aspects.map(x => `<span class="badge badge-ai">${escapeHtml(x)}</span>`).join(' ')}</p>` : ''}
            ${p.segments && p.segments.length ? `<details style="margin-top:0.5rem;"><summary style="cursor:pointer;">Segments (${p.segments.length})</summary>${p.segments.map(sg => `<p style="font-size:0.88rem;" lang="it"><strong>${sg.index + 1}.</strong> ${escapeHtml(sg.text)} <button type="button" class="link-button" data-inspect="${escapeAttr(sg.uri)}" style="font-size:0.78rem;">open</button></p>`).join('')}</details>` : ''}
            ${p.anchored_contributions && p.anchored_contributions.length ? `<h4 style="margin-top:1rem;"><i class="fas fa-comments"></i> Contributions anchored here (${p.anchored_contributions.length})</h4>${p.anchored_contributions.map(c => `<div class="annotation-card human"><div class="ann-head"><strong>${escapeHtml(c.author ? c.author.name : 'Unknown')}</strong>${(c.methods || []).map(m => `<span class="badge badge-condition">${escapeHtml(m === 'system_prediction' ? 'system anchor' : 'author anchor')}</span>`).join(' ')}<button type="button" class="link-button" data-inspect="${escapeAttr(c.uri)}" style="margin-left:auto;font-size:0.8rem;">open</button></div><div class="ann-body">${escapeHtml(c.text)}</div></div>`).join('')}` : '<p class="filters-help">No contribution is anchored to this provision.</p>'}
            ${p.change_proposals && p.change_proposals.length ? `<p style="font-size:0.9rem;"><strong>Change proposals targeting this provision:</strong> ${p.change_proposals.length}</p>` : ''}
            </div>`;
    }
    if (s.legal_document) {
        const d = s.legal_document;
        html += `<div class="inspect-section"><h4><i class="fas fa-book"></i> Legal document</h4>${d.expressions.map(e => `
            <div class="legal-doc-card"><p style="margin:0;"><strong>${escapeHtml(e.label)}</strong></p>
            <p class="mono" style="margin:0.3rem 0;color:var(--text-light);">expression ${escapeHtml(e.frbr_expression)}${e.frbr_manifestation ? ' • manifestation ' + escapeHtml(e.frbr_manifestation) : ''}${e.filename ? ' • ' + escapeHtml(e.filename) : ''}</p>
            ${e.processes && e.processes.length ? `<p style="font-size:0.9rem;">Consultation: ${e.processes.map(p => `<button type="button" class="link-button" data-process="${escapeAttr(p.uri)}">${escapeHtml(truncate(p.label, 80))}</button>`).join(', ')}</p>` : ''}
            <ul class="provision-list">${e.provisions.map(p => `<li><button type="button" data-inspect="${escapeAttr(p.uri)}">${escapeHtml(truncate(p.label, 70))} <span style="color:var(--text-light)">(${p.anchored_contributions} anchored)</span></button></li>`).join('')}</ul></div>`).join('')}</div>`;
    }
    if (s.participant) {
        const p = s.participant;
        html += `<div class="inspect-section"><h4><i class="fas fa-user"></i> Participant</h4>
            <div class="inspect-kv"><dt>Name</dt><dd>${escapeHtml(p.name)}</dd>${p.participant_type ? `<dt>Type</dt><dd>${escapeHtml(p.participant_type.replace(/_/g, ' ').toLowerCase())}</dd>` : ''}${p.condition_assignments && p.condition_assignments.length ? `<dt>Assigned conditions</dt><dd>${p.condition_assignments.map(x => `<span class="badge badge-condition">${escapeHtml(x)}</span>`).join(' ')}</dd>` : ''}<dt>Contributions</dt><dd>${p.contributions_count}</dd>${p.evaluations_made ? `<dt>Evaluations / actions recorded</dt><dd>${p.evaluations_made}</dd>` : ''}</div>
            ${p.note ? `<p style="font-size:0.85rem;color:var(--text-light);">${escapeHtml(p.note)}</p>` : ''}
            ${p.contributions.length ? `<h4 style="margin-top:0.8rem;">Contributions</h4>${p.contributions.map(c => `<div class="annotation-card human"><div class="ann-head">${c.kind ? `<span class="badge badge-type">${escapeHtml(KIND_LABELS[c.kind] || c.kind)}</span>` : ''}${c.timestamp ? `<span style="color:var(--text-light)">${escapeHtml(formatDateTime(c.timestamp))}</span>` : ''}<button type="button" class="link-button" data-inspect="${escapeAttr(c.uri)}" style="margin-left:auto;font-size:0.8rem;">open</button></div><div class="ann-body">${escapeHtml(c.text)}</div></div>`).join('')}` : ''}</div>`;
    }
    if (s.topic) {
        const t = s.topic;
        html += `<div class="inspect-section"><h4><i class="fas fa-tag"></i> Topic</h4><div class="inspect-kv"><dt>Label</dt><dd>${escapeHtml(t.label)}</dd>${t.description ? `<dt>Question / description</dt><dd>${escapeHtml(t.description)}</dd>` : ''}${t.top_terms ? `<dt>Top terms</dt><dd>${escapeHtml(t.top_terms)}</dd>` : ''}<dt>Contributions</dt><dd>${t.contributions_count}</dd>${t.expected_fallacies.length ? `<dt>Fallacies expected by design</dt><dd>${t.expected_fallacies.map(escapeHtml).join(', ')}</dd>` : ''}${t.processes.length ? `<dt>Process</dt><dd>${t.processes.map(p => `<button type="button" class="link-button" data-process="${escapeAttr(p.uri)}">${escapeHtml(truncate(p.label, 80))}</button>`).join(', ')}</dd>` : ''}</div>
            ${t.links && t.links.length ? `<h4 style="margin-top:0.8rem;">Links</h4><ul class="links-list">${t.links.map(linkItem).join('')}</ul>` : ''}</div>`;
    }
    if (s.link) {
        const l = s.link;
        html += `<div class="inspect-section"><h4><i class="fas fa-link"></i> Link</h4><div class="inspect-kv"><dt>Type</dt><dd><span class="badge badge-link-${escapeAttr(l.link_type)}">${escapeHtml(l.link_type)}</span> ${escapeHtml((l.relation || '').replace(/_/g, ' '))}</dd><dt>From</dt><dd>${l.source ? `<button type="button" class="link-button" data-inspect="${escapeAttr(l.source.uri)}">${escapeHtml(l.source.label)}</button>` : ''}</dd><dt>To</dt><dd>${l.target ? `<button type="button" class="link-button" data-inspect="${escapeAttr(l.target.uri)}">${escapeHtml(l.target.label)}</button>` : ''}</dd>${l.similarity != null ? `<dt>Similarity</dt><dd>${Number(l.similarity).toFixed(3)}</dd>` : ''}${l.method ? `<dt>Method</dt><dd>${escapeHtml(l.method)}${l.model ? ` (${escapeHtml(l.model)})` : ''}</dd>` : ''}</div>${l.note ? `<p class="notice notice-warn">${escapeHtml(l.note)}</p>` : ''}</div>`;
    }
    if (s.fallacy_type) {
        const f = s.fallacy_type;
        html += `<div class="inspect-section"><h4><i class="fas fa-flag"></i> Fallacy category</h4><div class="inspect-kv"><dt>Label</dt><dd>${escapeHtml(f.label)}</dd><dt>Category</dt><dd>${escapeHtml(f.macro_category)} / ${escapeHtml(f.fine_label)}</dd><dt>Question shown to participants</dt><dd>${escapeHtml(f.question)}</dd><dt>Example</dt><dd>${escapeHtml(f.example)}</dd><dt>Taxonomy</dt><dd>${escapeHtml(f.taxonomy_version)}</dd><dt>Annotations using it</dt><dd>${f.annotations_count}</dd></div></div>`;
    }
    if (s.platform) {
        const p = s.platform;
        html += `<div class="inspect-section"><h4><i class="fas fa-globe"></i> Platform</h4>${p.logo ? `<img src="${escapeAttr(p.logo)}" alt="${escapeAttr(p.logo_alt)}" style="max-height:70px;">` : ''}<p>${escapeHtml(p.description)}</p><div class="inspect-kv"><dt>Processes</dt><dd>${p.processes_count}</dd><dt>Contributions</dt><dd>${p.contributions_count}</dd>${p.url ? `<dt>Website</dt><dd><a href="${escapeAttr(p.url)}" target="_blank" rel="noopener">${escapeHtml(p.url)}</a></dd>` : ''}</div>${p.processes && p.processes.length ? `<ul>${p.processes.map(pr => `<li><button type="button" class="link-button" data-process="${escapeAttr(pr.uri)}">${escapeHtml(pr.title)}</button></li>`).join('')}</ul>` : ''}</div>`;
    }
    if ((r.links || []).length && !s.topic) {
        html += `<div class="inspect-section"><h4><i class="fas fa-link"></i> Links (${r.links.length})</h4><ul class="links-list">${r.links.map(linkItem).join('')}</ul></div>`;
    }

    // Technical view: raw properties and incoming references
    const props = r.properties || {};
    const inc = r.incoming || {};
    html += `<div class="inspect-section"><h4><i class="fas fa-code"></i> Technical details</h4>
        <p class="mono" style="margin:0 0 0.5rem;"><a href="${escapeAttr(r.uri)}" target="_blank" rel="noopener">${escapeHtml(r.uri)}</a></p>
        <button type="button" class="raw-toggle" aria-expanded="false" data-raw-toggle>Show all RDF properties (${Object.keys(props).length}) and incoming references (${Object.values(inc).reduce((n, v) => n + v.length, 0)})</button>
        <div class="raw-table" data-raw>
            ${Object.entries(props).sort().map(([k, vals]) => `<div class="resource-property"><div class="resource-property-name">${escapeHtml(k)}</div><div class="resource-property-value">${vals.map(v => v.uri ? `<div><button type="button" class="link-button" data-inspect="${escapeAttr(v.uri)}">${escapeHtml(v.label || v.uri)}</button> <span class="mono" style="color:var(--text-light)">${escapeHtml(v.uri)}</span></div>` : `<div>${escapeHtml(String(v.value))}${v.lang ? ` <span class="badge badge-condition">${escapeHtml(v.lang)}</span>` : ''}</div>`).join('')}</div></div>`).join('')}
            ${Object.entries(inc).sort().map(([k, vals]) => `<div class="resource-property"><div class="resource-property-name">← ${escapeHtml(k)}</div><div class="resource-property-value">${vals.map(v => `<div><button type="button" class="link-button" data-inspect="${escapeAttr(v.uri)}">${escapeHtml(v.label || v.uri)}</button>${v.text ? ` <span style="color:var(--text-light)">– ${escapeHtml(truncate(v.text, 100))}</span>` : ''}</div>`).join('')}</div></div>`).join('')}
            <p style="font-size:0.85rem;margin-top:0.6rem;">Query this resource with SPARQL on the <a href="${DKG_BASE}/sparql.html" target="_blank" rel="noopener">DKG SPARQL interface</a>; dereference the URI with <code>Accept: text/turtle</code> for RDF.</p>
        </div></div>`;
    modalBody.innerHTML = html;
    bindInspectButtons(modalBody);
    const tgl = modalBody.querySelector('[data-raw-toggle]');
    if (tgl) tgl.addEventListener('click', () => { const t = modalBody.querySelector('[data-raw]'); const open = t.classList.toggle('open'); tgl.setAttribute('aria-expanded', open ? 'true' : 'false'); });
    modalBody.scrollTop = 0;
    document.getElementById('resourceModal').querySelector('.modal-content').scrollTop = 0;
}

function formatDateTime(v) {
    if (!v) return '';
    try { const d = new Date(v); if (isNaN(d.getTime())) return String(v); return d.toISOString().slice(0, 16).replace('T', ' ') + ' UTC'; } catch (e) { return String(v); }
}

// Close modal when clicking the backdrop
window.addEventListener('click', function (event) {
    const modal = document.getElementById('resourceModal');
    if (event.target === modal) closeResourceModal();
});
